/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;
import static org.junit.Assert.*;

public class OvenTest {

    @Test public void testOvenConstructor_1() {
        Oven ov = new Oven();
        assertEquals(320, ov.getMaxTemperature());

    }


    @Test(expected = IllegalArgumentException.class)
    public void testOvenConstructor_2() {
        Oven ov = new Oven(-1);
    }

}
