/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package breaker;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    App classUnderTest = new App();
    @Test public void testAppArrays() {
        
        assert (classUnderTest.balls != null ) : "balls array" ;
        assert ( classUnderTest.paddles != null ): "paddles array";
        assert ( classUnderTest.bricks != null) : "bricks array";
        assert ( classUnderTest.magic != null) : "bricks array";
        
    }
    
    
    
}
